# Generated by Django 5.1.7 on 2025-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatube', '0003_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ваше имя')),
                ('email', models.CharField(max_length=30, verbose_name='ваш email')),
                ('text', models.TextField(verbose_name='текст обращения')),
            ],
        ),
    ]
