# Generated by Django 5.1.6 on 2025-06-09 15:51

import yatube.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatube', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_name',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, validators=[yatube.validators.validation], verbose_name='ваш email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=100, validators=[yatube.validators.validation], verbose_name='ваше имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(validators=[yatube.validators.validation], verbose_name='текст обращения'),
        ),
    ]
