# Generated by Django 5.1.6 on 2025-06-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatube', '0005_group_user_name_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user_name',
            field=models.CharField(max_length=15),
        ),
    ]
