# Generated by Django 5.1.6 on 2025-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatube', '0006_alter_group_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
