# Generated by Django 5.1.6 on 2025-06-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatube', '0009_alter_group_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'description')},
        ),
    ]
